IF OBJECT_ID(N'dbo.ZZ_NF_GAS_QC_ERROR_LOG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ZZ_NF_GAS_QC_ERROR_LOG
    (
        SID UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT DF_ZZ_NF_GAS_QC_ERROR_LOG_SID DEFAULT NEWID(),

        OCCURRED_AT DATETIME NOT NULL,
        LAST_OCCURRED_AT DATETIME NOT NULL,
        OCCURRENCE_COUNT INT NOT NULL,

        LOGICAL_BATCH_DATE NVARCHAR(32) NULL,
        PORT NVARCHAR(32) NULL,
        TOP_FOLDER_NAME NVARCHAR(255) NULL,
        LOT_NO NVARCHAR(64) NULL,
        QUANT_PATH NVARCHAR(1024) NOT NULL,
        SOURCE_KEY_HASH VARBINARY(32) NOT NULL,
        DATA_FOLDER_PATH NVARCHAR(1024) NULL,
        ERROR_TYPE NVARCHAR(128) NOT NULL,
        MESSAGE NVARCHAR(MAX) NOT NULL,
        SUGGESTED_ACTION NVARCHAR(MAX) NULL,

        CREATE_USER NVARCHAR(64) NOT NULL
            CONSTRAINT DF_ZZ_NF_GAS_QC_ERROR_LOG_CREATE_USER DEFAULT N'GasQcDataLoader',
        CREATE_TIME DATETIME NOT NULL
            CONSTRAINT DF_ZZ_NF_GAS_QC_ERROR_LOG_CREATE_TIME DEFAULT GETDATE(),
        EDIT_USER NVARCHAR(64) NULL,
        EDIT_TIME DATETIME NULL,

        CONSTRAINT PK_ZZ_NF_GAS_QC_ERROR_LOG PRIMARY KEY (SID)
    );
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'UX_ZZ_NF_GAS_QC_ERROR_LOG_SOURCE'
      AND object_id = OBJECT_ID(N'dbo.ZZ_NF_GAS_QC_ERROR_LOG', N'U')
)
BEGIN
    CREATE UNIQUE INDEX UX_ZZ_NF_GAS_QC_ERROR_LOG_SOURCE
    ON dbo.ZZ_NF_GAS_QC_ERROR_LOG (SOURCE_KEY_HASH);
END;
