IF OBJECT_ID(N'dbo.ZZ_NF_GAS_QC_LOT_STD_QC', N'U') IS NULL
BEGIN
    SELECT TOP (0) *
    INTO dbo.ZZ_NF_GAS_QC_LOT_STD_QC
    FROM dbo.ZZ_NF_GAS_QC_LOT_STD_RPD;
END;

IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'ZZ_NF_GAS_QC_LOT_STD_QC'
      AND COLUMN_NAME = 'ID'
      AND (CHARACTER_MAXIMUM_LENGTH IS NULL OR CHARACTER_MAXIMUM_LENGTH < 255)
)
BEGIN
    ALTER TABLE dbo.ZZ_NF_GAS_QC_LOT_STD_QC
    ALTER COLUMN ID nvarchar(255) NULL;
END;
