IF OBJECT_ID(N'dbo.ZZ_NF_GAS_QC_QUERY2_PREVIEW_EDIT_LOG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ZZ_NF_GAS_QC_QUERY2_PREVIEW_EDIT_LOG
    (
        SID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZZ_NF_GAS_QC_QUERY2_PREVIEW_EDIT_LOG PRIMARY KEY,
        ExportSessionId UNIQUEIDENTIFIER NOT NULL,
        ExcelExportKey NVARCHAR(64) NOT NULL,
        StartDate DATE NOT NULL,
        EndDate DATE NOT NULL,
        RfId NVARCHAR(200) NOT NULL,
        StdRawIds NVARCHAR(MAX) NOT NULL,
        PortRawIds NVARCHAR(MAX) NOT NULL,
        RowKey NVARCHAR(40) NOT NULL,
        RowType NVARCHAR(20) NOT NULL,
        RowDisplayId NVARCHAR(200) NULL,
        FieldKey NVARCHAR(200) NOT NULL,
        ValueKind NVARCHAR(20) NOT NULL,
        Analyte NVARCHAR(100) NOT NULL,
        OriginalValue NVARCHAR(100) NULL,
        NewValue NVARCHAR(100) NULL,
        ExportedAt DATETIME2(3) NOT NULL,
        ExportUser NVARCHAR(100) NOT NULL,
        CreateTime DATETIME2(3) NOT NULL
    );

    CREATE INDEX IX_ZZ_NF_GAS_QC_QUERY2_PREVIEW_EDIT_LOG_ExportSessionId
        ON dbo.ZZ_NF_GAS_QC_QUERY2_PREVIEW_EDIT_LOG (ExportSessionId);

    CREATE INDEX IX_ZZ_NF_GAS_QC_QUERY2_PREVIEW_EDIT_LOG_ExcelExportKey
        ON dbo.ZZ_NF_GAS_QC_QUERY2_PREVIEW_EDIT_LOG (ExcelExportKey, ExportedAt);
END;
